version: '3.8'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    ports:
      - target: 8079
        published: 80
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  carts-db:
    image: mongo:3.4
    hostname: carts-db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  orders-db:
    image: mongo:3.4
    hostname: orders-db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    hostname: shipping
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  user:
    image: weaveworksdemos/user:0.4.4
    hostname: user
    environment:
      - MONGO_HOST=user-db:27017
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
